### ISSUE TITLE
Crash due to validation issue

### ISSUE THREAD

**Issue by nbenn** [blockr-org/blockr#101]
Playing with externally registered block, I ran into a crash which feels like caused by validation. Can be reproduced as:

https://github.com/blockr-org/blockr/blob/4480c6ba5d15db8648a3b139ec684412d25e3c5a/inst/testdata/test.registry/README.md?plain=1#L23-L29

The problem is

https://github.com/blockr-org/blockr/blob/bd45e2aeda1b7c66ed6f3a14471487b9a443d304/R/utils.R#L306

when `val` is `NA`, `nchar(val)` is `NA` and `all(NA)` is `NA` as well. This has to be made more robust. Also, it looks like we have a parenthesis typo in there too. Should it not be `all(nchar(val) == 0)` instead of `all(nchar(val)) == 0`?

**Comment by DivadNojnarg** [comment]
Thanks @nbenn: I actually totally overlooked this case (numericInput returns NA when no value is inside, whereas a select returns NULL when multiple is TRUE and a textInput is "").
