### ISSUE TITLE
Move non-core blocks out of blockr

### ISSUE THREAD

**Issue by nbenn** [blockr-org/blockr#103]
There are currently quite a few blocks that I would not consider "core blocks" (e.g. all of `demo-block.R` or for example the `ggiraph_block` which seems very specialized.

Apart from fairly obvious candidates, some cases are less clear. The `head_block` for example adds little value in my mind. I propose two things:

- we have a discussion on what we feel are core blocks
- someone (myself? @DivadNojnarg) cleans up (i.e. moves) demo blocks to another package

Not high prio, but reducing some clutter might be good for maintenance.

**Comment by nbenn** [comment]
Related discussion https://github.com/blockr-org/blockr/discussions/105

**Comment by DivadNojnarg** [comment]
This sounds reasonable. We could even be stricter and only keep in blockr what is related to the infrastructure (constructors, fields, ..., data block). 

filter_block, select_block, ... would move to this new package.

**Comment by DivadNojnarg** [comment]
Yes the data.block is a bit special and I would leave it in the core (not specific to dplyr or admiral,...). This block should be able to read data from various locations (DB, local, file, GPSII, ...). If we go for a `block.dplyr`, base-R function blocks like head should perhaps be kept in the core (1 at the moment).

**Comment by DivadNojnarg** [comment]
Closing, the first round has been done. Will create another issue if we do an extra cleanup.
