### ISSUE TITLE
Single remove block input

### ISSUE THREAD

**Issue by DivadNojnarg** [blockr-org/blockr#115]
Currently, if we want to remove a block, we click on the block remove button which is `input$<stack_ID>_<block_ID>_remove`. However, this is not very convenient to handle on the server side since we have to setup many observeEvent (one per button) and this is not ideal when adding new blocks. I would prefer having a single `input$<stack_id>_block_remove` which holds the index of the block to remove. Ideally, when we click on any remove button, we call `Shiny.setInputValue('<stack_id>_block_remove', block_index)` in an `onclick` event. This would allow to get rid of the "last "input changed" [workaround](https://github.com/blockr-org/blockr/issues/25). 

Let me know what you think @JohnCoene

**Comment by nbenn** [comment]
@DivadNojnarg A (semi) related issue might be that of name/ID responsibility: #112

Currently a block ID is a property of the block. Maybe it'd be better to have this be a property of the stack? Something we should discuss.
