### ISSUE TITLE
Implement shiny logic part for workspace

### ISSUE THREAD

**Issue by DivadNojnarg** [blockr-org/blockr#121]

**Comment by DivadNojnarg** [comment]
As discussed last week with @JohnCoene, to clarify, this is only needed by blockr to provide a minimal standalone starting point. In his higher level demo, @JohnCoene only needs the blockr backend workspace functions to develop more elaborated UI.

**Comment by JohnCoene** [comment]
I need to be able to regenerate individual stack objects from the serialised workspace so that I can subsequently generate UI and server for each respective stacks.
