### ISSUE TITLE
set_workspace_stacks error

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#123]
Perhaps I'm using wrong.

```r
stack <- new_stack(data_block)

set_workspace_stack(stack)
#> Error in set_workpsace_stacks(stack) : !is.null(nms) is not TRUE

set_workpsace_stacks(list(stack, stack))
#> Error in set_workpsace_stacks(stack) : !is.null(nms) is not TRUE
```

**Comment by JohnCoene** [comment]
OK, confused as to what the stacks names are meant to represent here, can you enlighten me?

**Comment by nbenn** [comment]
@JohnCoene stack names are how stacks can be identified. It's like the IDs for blocks and an improvement here might be that if not user-specified, some random names are used instead.

All of this is also related to #112, where we currently have a bit of a mess in that a block ID is part of the block itself, which I don't think I got right in the first iteration: Handing out IDs should be the responsibility of the stack to also guarantee uniqueness.
