### ISSUE TITLE
Block UI issues

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#136]
I don't thing this line is correct

https://github.com/blockr-org/blockr/blob/cbb1b67c23f42ae6333e760a58e2c62f8c3e2813/R/ui.R#L235

This prepends to `.block-tools`, it does not place it within the `div`

![image](https://github.com/blockr-org/blockr/assets/7833796/78724b02-2a3f-4e26-afc5-8e9d68d2a006)

Also, shouldn't the `.block-tools` be within the parent `flex`?

**Comment by DivadNojnarg** [comment]
I spotted another issue while playing with dynamic blocks. The delete button is missing because it is added only from the stack once. 

<img width="1035" alt="Screenshot 2023-12-21 at 17 03 04" src="https://github.com/blockr-org/blockr/assets/18291543/374336e5-71be-4a32-8987-739f8cca004e">

**Comment by JohnCoene** [comment]
The show code at the block-level has also disappeared

**Comment by JohnCoene** [comment]
Closing this I think it's been tackled, we can open separate, more focused, issues if anything else is still to do
