### ISSUE TITLE
Data Block: read data from disk

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#149]
We're going to need a block that allows reading data from disk.

This can be implemented a number of ways. The user should be able to select a dataset from a directory.

Note that we should be able to handle multiple data formats, e.g.: `csv`, `xpt`, `sas7bdat`

**Comment by DivadNojnarg** [comment]
@JohnCoene: do you expect the user to also browse the directory? For instance having access to the file system while using the tool. `{shinyFiles}` does this, however, we'd have to create extra fields and so ...

**Comment by JohnCoene** [comment]
Yes, being able to browse files would be good I guess.

I have a feeling that shiny module is not ideal for fields. maybe we can build something on top of [this](https://github.com/cubiclesoft/js-fileexplorer) (or any other library) instead?

What do you think?

**Comment by nbenn** [comment]
@DivadNojnarg I'm for adding this as a regular new field, something like `upload_field` or so. Does not shiny provide `fileInput()` (which would be called in `ui_input.upload_field()`) out of the box? Or is that no good for some reason?

If you want to add shinyFiles as regular field, what I do in

https://github.com/blockr-org/blockr/blob/979a176435a493712d99d6741961108954b7297f/R/ui.R#L557-L585

might be helpful. You can of course also use the field-server stuff from @christophsax , but I don't believe this is necessary only for registering an observer.

If you want me to expand on what I do in the above snippet, let me know. If you cannot make the above work in the non-field-server setting, this would interest me as well.

**Comment by DivadNojnarg** [comment]
Can we gather #149 and #148 in that case?

**Comment by nbenn** [comment]
@DivadNojnarg sorry, I started mixing things up there. I guess `upload_field` and `file_field` can be two separate things. I did not pay close attention and thought files would be client-provided and that shinyFiles was just a fancy (client-side) file browser.

Is server-side file browsing really a requirement @JohnCoene? I know nothing about the BMS infra, but I'd imagine that such files are not actually on a server-local filesystem.

**Comment by JohnCoene** [comment]
Yes, they are on the a drive mounted on the Connect Server so we need a new field/block for users to select the appropriate file from disk

**Comment by nbenn** [comment]
Ok, then I guess we need both an `upload_field` and a `file_field` (or whatever better names we can come up with).

For the data block we could then implement this (just an idea) using a `variable_field` and a `switch_field` where the switch is between "client" and "server" file system and the `variable_field` is materialized either as `upload_field` or `file_field` depending on the toggle state.

**Comment by DivadNojnarg** [comment]
I tried using the `variable_field`, which seemed to render well at first look. However, there are few issues:
- Neither the upload input or shinyFiles render well within a `variable_field`. The fileInput does nothing when selecting the file (no progress is shown) and shinyFiles fails to render the file browser (contrary to my previous screenshot).
- shinyFiles registers observeEvents, which can't be removed by the `ui_update.variable_field`. Therefore, after changing the switch input, shinyFiles modal fires multiple times. 

I'll give it some time for debugging.

**Comment by DivadNojnarg** [comment]
Code for file loader block with `variable_field` (not working):


```r
new_fileloader_block <- function(...) {

  field_type <- function(file_mode) {
    if (file_mode) "upload_field" else "filesbrowser_field"
  }

  #field_args <- quote()

  read_data <- function(dat, file_mode) {
    if (length(dat) == 0 || is.integer(dat) || length(dat$files) == 0) {
      cat("No files have been selected yet.")
      return(data.frame())
    }

    # TO DO: remove hardcoded volumes (how to send this to ui_update part?)
    volumes <- c(home = path.expand("~"))
    files <- shinyFiles::parseFilePaths(volumes, dat)
    data_func <- utils::read.csv # TO DO switch

    bquote(
      .(read_func)(.(path)),
      list(read_func = data_func, path = files$datapath)
    )
  }

  new_block(
    fields = list(
      file_mode = new_switch_field(),
      dat = new_variable_field(
        field = field_type,
        components = list()
      ),
      expression = new_hidden_field(read_data)
    ),
    expr = quote(.(expression)),
    ...,
    class = c("fileloader_block", "data_block")
  )
}

fileloader_block <- function(...) {
  initialize_block(new_fileloader_block(...))
}
```
