### ISSUE TITLE
Validation should in no way depend on field names

### ISSUE THREAD

**Issue by nbenn** [blockr-org/blockr#163]
With the current validation setup, we have exclusion criteria that are hard-coded to field names. These are completely arbitrary and this logic in

https://github.com/blockr-org/blockr/blob/5d2cfcdee04b40df0a037c8bacdcb8bcd8f44897/R/utils.R#L305

should not depend on this. I just created a block where I was using a hidden field that was not called `expression` but `expr_parsed` and for a block like this, the submit button will be permanently disabled. Happy to create a reprex, but I don't think it's necessary.

**Comment by christophsax** [comment]
Reprex in the linked PR #203

**Comment by DivadNojnarg** [comment]
Fixed in 0.0.2
