### ISSUE TITLE
Filter block: validation error on add

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#165]
When we add a filter_block to an existing tag we are prompted with this:

![image](https://github.com/blockr-org/blockr/assets/7833796/d955aba1-83f6-4835-9df6-cbc2d95908ae)

Also, I'm not sure we should really interrupt the user with a modal, there is already ample feedback when there is an error in a block.

**Comment by DivadNojnarg** [comment]
To remove from `secure` in utils.R

**Comment by DivadNojnarg** [comment]
This error is not relevant anymore in main because `secure` is not being used when attempting to update a block (therefore no error is thrown).
