### ISSUE TITLE
Remove/add block broken with latest PR

### ISSUE THREAD

**Issue by DivadNojnarg** [blockr-org/blockr#173]
It seems that this function has been removed in the latest PR #146, the conflict resolution isn't correct: 

See https://github.com/blockr-org/blockr/pull/146/commits/b4e2ac98ed7b0c25ea86b4702d3cbb04c4e5c228#diff-9e95b340633529fb09e594e8e485b849dac8a3aa0d81017be4c7556d34bfb05bL252-L283.

We also can't add new block because `handle_remove_block` is called within the stack but not defined.

```r
Error in handle_remove_block: could not find function "handle_remove_block" 
```

The app is currently unusable (cc @JohnCoene). Can you revert this @christophsax? I did not check everything but there might be other problems.

**Comment by DivadNojnarg** [comment]
The last valid state of the app is: https://github.com/blockr-org/blockr/tree/a985dc9c56595493349045a759a52d366da317d5

**Comment by christophsax** [comment]
We can revert my PR. I think I haven't merged it properly.

**Comment by christophsax** [comment]
I did a PR that brings the function back (#175). Does that fix the problem?
