### ISSUE TITLE
Documentation: tutorial how to create a plot block (layer by layer)

### ISSUE THREAD

**Issue by DivadNojnarg** [blockr-org/blockr#174]
This will be needed by @karmatarap 's team next week.

**Comment by DivadNojnarg** [comment]
@JohnCoene: Feel free to start something based on the discussion https://github.com/blockr-org/blockr/discussions/153 if you have some time. I still have to review your PR and finish the data blocks.

**Comment by christophsax** [comment]
I am gonna do a small vignette on Admiral blocks: https://github.com/blockr-org/blockr/issues/195. We may explore some overlap later on.

**Comment by DivadNojnarg** [comment]
If you're too busy with other issues (serialisation, ...) @JohnCoene I can handle this. I am mostly done with the doc refactoring in #201.

**Comment by JohnCoene** [comment]
Thank you David!

If you have time it would be great indeed. I have a lot to do with serialisation and all other packages.
