### ISSUE TITLE
Error in `update_sub_fields()` when calling on zero-length `list_field`

### ISSUE THREAD

**Issue by nbenn** [blockr-org/blockr#179]
With the new block-level server logic and a (malformed) app startup as

```r
stack1 <- new_stack(
  new_data_block,
  new_filter_block
)

serve_stack(stack1)
```

we have in

https://github.com/blockr-org/blockr/blob/79a95813741e7fe234780a1819c0442df275fad2/R/field.R#L396-L407

the situation where `sub` is `NULL` and `val` is `chr(0)`. In my original implementation we had

https://github.com/blockr-org/blockr/blob/bf7ae805bed2546b3d5aec1efec5bec5fd2b4a34/R/field.R#L314-L316

which can handle such a situation, but the newer `if(is.null(names(val)))` branch ofc errors on invalid subsetting. For the sake of improving the safety of our code-base, we should at least do something like

```r
if (is.null(names(val)) && length(sub)) {
  value(sub[[1]]) <- unlist(val)
} else {
  for (fld in names(val)[lgl_ply(val, is_truthy)]) {
    value(sub[[fld]]) <- unlist(val[[fld]])
  }
}
```

but maybe we can improve even more. Do you remember @DivadNojnarg what the precise reason was to add `value(sub[[1]]) <- unlist(val)`? Maybe my proposal should be even more specific (i.e. `length(sub) == 1L`)? Otoh if (in `new_join_block()`) the `list_field` called `by` is always length 1, what was the reason to implement this as `list_field` in the first place?

**Comment by DivadNojnarg** [comment]
@nbenn from my comment, it was for the `join_block` before our very first demo. That said, I can rewrite the join_block like this and not use the `list_field` (I don't recall why I did this). 

```r
new_join_block <- function(
    data,
    y = data(package = "blockr.data")$result[, "Item"],
    type = character(),
    by_col = character(),
    ...) {

  # by depends on selected dataset and the input data.
  choices <- intersect(
    colnames(data),
    colnames(eval(as.name(y)))
  )

  default <- if (length(choices) == 0) {
    character()
  } else {
    if (length(by_col) > 0) {
      by_col
    } else {
      choices[[1]]
    }
  }

  join_expr <- function(data, join_func, y, by) {
    if (length(by) == 0) stop("Nothing to merge, restoring defaults.")
    bquote(
      .(join_func)(y = .(y), by = .(by)),
      list(join_func = as.name(join_func), y = as.name(y), by = by)
    )
  }

  join_types <- c(
    "left",
    "inner",
    "right",
    "full",
    "semi",
    "anti"
  )

  if (length(type) == 0) type <- join_types[1]

  fields <- list(
    join_func = new_select_field(
      paste(type, "join", sep = "_"),
      paste(join_types, "join", sep = "_")
    ),
    y = new_select_field(y[[1]], y),
    by = new_select_field(default, choices, multiple = TRUE),
    expression = new_hidden_field(join_expr)
  )

  attr(fields$y, "type") <- "name"
  # TO DO: expression is ugly: try to get rid of get and
  # unlist.
  expr <- quote(.(expression))

  new_block(
    fields = fields,
    expr = expr,
    ...,
    class = c("join_block", "transform_block", "submit_block"),
    layout = join_layout_fields
  )
}
```

Therefore, I am fine with either restoring the old condition/improving it.

**Comment by DivadNojnarg** [comment]
Not relevant anymore in 0.0.2
