### ISSUE TITLE
Dataset change in demo example crashes

### ISSUE THREAD

**Issue by nbenn** [blockr-org/blockr#182]
@christophsax I have a new one for you: with current main and using our standard demo example (this time with the intended constructors) I get with

```r
stack <- new_stack(
  data_block,
  filter_block
)

options("BLOCKR_DEV" = TRUE)
serve_stack(stack)
```

an immediate crash when changing datasets. Let me know if you have trouble reproducing.

https://github.com/blockr-org/blockr/assets/3158446/99a34580-8423-448d-8d71-30d194eddf78

**Comment by DivadNojnarg** [comment]
That's because the `secure` function was dropped when updating a block. Before we [had](https://github.com/blockr-org/blockr/blob/a985dc9c56595493349045a759a52d366da317d5/R/server.R#L123):

```r
obs$update_block <- observeEvent(
        eval(obs_expr(blk())),
        {
          secure(eval(set_expr(blk())), is_valid)
          message(sprintf("Updating block %s", class(x)[[1]]))
        },
        ignoreInit = TRUE
      )
```

where `secure` (tryCatch + custom message) prevented to crash the app when changing the dataset. This is independent of using `options("BLOCKR_DEV" = TRUE)`.

**Comment by DivadNojnarg** [comment]
As a test, I reintroduced a `try` but the subsequent blocks are not updated. So there is another issue.

<img width="1346" alt="Screenshot 2024-01-12 at 18 38 32" src="https://github.com/blockr-org/blockr/assets/18291543/2ab348cf-d1f6-4b96-ad2e-30d2e3f4aed6">

**Comment by nbenn** [comment]
A couple of comments on this:

- The problem we have here boils down to the situation in `update_blk()` for the `filter_block`, where
    1. the `data` has changed to the new dataset ("anscombe")
    2. values passed as `value` are stale (stuff collected from input is still using "old" values)
    3. `update_field()` is called with conflicting information
    4. the filter block-supplied function `sub_fields()` errors, b/c it tries to determine the type of column "Ozone" in the data.frame "anscombe"
- In my initial implementation (somewhere around 10bc779), this was explicitly handled something like

    https://github.com/blockr-org/blockr/blob/10bc779d852823a1c583a309a5d588969e3ae08b/R/field.R#L110-L120

    I explicitly handle such inconsistencies be re-setting the selection (to the first choice) and all is good again.
- This behavior was lost over time (329e86928bb7e4952a117fcd348bbf4bfc93219d, 70c78d56e45c3f6033f265a96f9279c37a63a02f and e119adadecfd2ef081bb483907da0cb9d13db784) and to address the underlying issue, the entire update process was wrapped in a big `tryCatch()`.
- In principle, wrapping evaluation of block-level expressions in a try-catch sounds like a good idea to me (especially with user supplied expressions; crashing out of the app due to a typo will not lead to a satisfying user experience).
- In this case, I don't believe `tryCatch()`ing the entire update process is a good idea. This yields to objects in an inconsistent state (you have data "anscombe" but a filter expression based on column "Ozone". My choice of resetting to the first choice was also not great as this is rather arbitrary. Maybe the smart thing to do here would be to reset to default (i.e. no column selection at all)?

One problem I saw with my initial implementation was that "validation" and "error correction" were combined operations (for the reason that they do share some logic). But this was probably a poor choice. A better approach could be that we have something like `validate()` and `reset_invalid_field()`.

Initially exactly this was tracked in https://github.com/blockr-org/blockr/issues/13 and then morphed into general discussions on validation (e.g. https://github.com/blockr-org/blockr/discussions/110). This should be revisited I believe.

**Comment by nbenn** [comment]
@christophsax can you comment on

https://github.com/blockr-org/blockr/blob/ff1d095479aaa37d970f66880be7b83ceb502da6/R/server.R#L31

I don't understand the purpose of explicitly jumping to the next loop iteration at the very end of the current.

If you did this earlier, it might be even worse, as you could potentially skip even though changes could still be introduced via `env`.

**Comment by christophsax** [comment]
Yes, that makes no sense. Really don't know why it's there. We can remove it.

**Comment by christophsax** [comment]
@DivadNojnarg can you check if still open, or close.
