### ISSUE TITLE
`options("BLOCKR_DEV" = TRUE)` no longer working?

### ISSUE THREAD

**Issue by christophsax** [blockr-org/blockr#202]
When doing something like that, I used to get expanded blocks, which was very useful for development. 
```r
library(blockr)
library(blockr.data)

stack <- new_stack(
  data_block,
  filter_block
)

options("BLOCKR_DEV" = TRUE)
serve_stack(stack)
```

This doesn't seem to work anymore, instead, I get:

<img width="1260" alt="image" src="https://github.com/blockr-org/blockr/assets/1390827/b7e5df28-b80b-432d-afff-ee097d0d4b29">

**Comment by christophsax** [comment]
Any idea, @DivadNojnarg?

**Comment by JohnCoene** [comment]
This is might be linked to the inject rénové button?

**Comment by DivadNojnarg** [comment]
This feature is handled [here](https://github.com/blockr-org/blockr/blob/main/R/server.R#L292), [here](https://github.com/blockr-org/blockr/blob/main/R/server.R#L292), [here](https://github.com/blockr-org/blockr/blob/main/R/ui.R#L178). This parameters is not used as I see (not in the function body) so you can reintroduce it and make sure it does not break the default (which was recently broken).
