### ISSUE TITLE
Error handling: adding blocks

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#213]
Currently, using the `new_block` reactive adding a block that isn't a dataset block as first block in a stack leads to a crash

```r
Warning: Error in add_block: The first block must be a data block.
```

This probably due to this

https://github.com/blockr-org/blockr/blob/54c027d415fa576a2992d259f07c3fc294acb698/R/stack.R#L73

There's no way, as far as I can tell, to handle that from outside the stack server.

I can "hardcode" a rule on the app end to check the block type before it is added but its likely going to cause issues in the long-term.

**Comment by DivadNojnarg** [comment]
Closing as #214 is more global (avoid duplicate issues).
