### ISSUE TITLE
registry: include all / more blocks

### ISSUE THREAD

**Issue by christophsax** [blockr-org/blockr#223]
- Adding blocks from blockr is easy
- Think about how to include blocks, e.g., from blockr.extra

**Comment by JohnCoene** [comment]
This would also be needed for the demo.

**Comment by DivadNojnarg** [comment]
@JohnCoene Adding an on load to `blockr.extra` would work right? Something like:

```r
.onLoad <- function(libname, pkgname) {

  register_blockr_blocks(pkgname)

  invisible(NULL)
}
```

so you only need to load blockr.extra.

**Comment by JohnCoene** [comment]
I believe so. That's how we register blocks in blockr, and how I register custom blocks in blockr.app

https://github.com/blockr-org/blockr/blob/0a4696821d9c48992131c69ab66bfbf6bd72dfd4/R/zzz.R#L1
