### ISSUE TITLE
Support additional datatypes (upload_block)

### ISSUE THREAD

**Issue by karmatarap** [blockr-org/blockr#224]
Please include sas7bdat and xpt as supported filetypes. Please use the haven package

**Comment by nbenn** [comment]
@DivadNojnarg what are your thoughts on how to add more supported file types?

- An easy thing to do is having a select with a couple of supported types "hard coded".
- A more modular approach could be decoupling "file uploading/selecting" and "parsing" into separate steps for which separate blocks are responsible.

For the latter option, the return object of `upload_block`/`filesbrowser_block ` would be a string (file path) and then any block could be added to parse that file. That way, when someone wants to parse an unsupported type, they do not have to reinvent that whole thing from scratch or require a core change which over time will add (too) many dependencies.

Just some thoughts on the matter from my end. Let me know if you want to discuss.

**Comment by DivadNojnarg** [comment]
@nbenn. I'd be ok to try out the second approach. Right now, this would leave us with 3 parsers: csv, sas, xpt.
