### ISSUE TITLE
Workspace updating

### ISSUE THREAD

**Issue by nbenn** [blockr-org/blockr#226]
This is split off of #221 and concerns

> I think most of the workspace handling could be internalised within {blockr}, we need to update the workspace when a block is added, removed to a stack or when a block is updated. All of this can be observed within blockr but I currently have to handle that outside of blockr.

**Comment by nbenn** [comment]
@DivadNojnarg As discussed: could you commit the required changes for reproducing the problem to the `128-serialize` branch and push (if you want, as new branch, or directly into the existing one).

**Comment by DivadNojnarg** [comment]
Done [here](https://github.com/blockr-org/blockr/pull/129/commits/1dd476ac16259329edbdf7f2520cb5bcbfc45c43)

**Comment by nbenn** [comment]
@DivadNojnarg Looking a the code a bit, it seems to me that the problem might come from how in `generate_server.workspace()` we never update the workspace with changes in stacks. Stacks are only *added* to the workspace, but never *updated*. We might at some point have to consider the efficiency of such a simplistic approach, but for a first iteration, couldn't we just have a reactive dep on all the stacks and update the workspace if any change?

Some modifications I'd like to make (to discuss later):

- Currently `generate_server.stack()` returns `vals` which is 

    https://github.com/blockr-org/blockr/blob/a487403f18f764e57db1c8a444a5da3b94e59b31/R/server.R#L251-L254
    I don't understand `blocks`. Could we have the stack server function just return a stack `reactiveValue`? This is not strictly necessary but it'd be a bit cleaner an API, no?
- In the workspace server function we then hold onto reactive versions of all stacks, as returned in
    https://github.com/blockr-org/blockr/blob/a487403f18f764e57db1c8a444a5da3b94e59b31/R/server.R#L489-L493
    and on any update call `set_workspace_stacks()`. Might not be terribly efficient but let's take it step by step.
- What should `generate_server.workspace()` return? A reactive version of the workspace? How would the return value of the workspace server function be used anyways`
