### ISSUE TITLE
UI: adding intermediate component -> step

### ISSUE THREAD

**Issue by DivadNojnarg** [blockr-org/blockr#23]
We currently reason in term of stack and blocks. However, after spending some time building blocks, I realise this is not convenient to use from the UI side. A block is currently a card (collapsible or not) which becomes messy (too much vertical space taken when there are many of them ...

Instead, I would think more about having an intermediate UI layer: step.
We would essentially have:

- The stack (same).
- 3 steps: data, transform, visualize.
- Individual blocks with classes allowing to put them into steps.

Doing like this would help to drag and drop blocks and fix rules governing where blocks can go. For instance, we could not drag a plot block in the data step and inversely ... (I guess this will be helpful for @JohnCoene later).

**Comment by christophsax** [comment]
Discussed
