### ISSUE TITLE
Update block

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#232]
_This is still being explored, keep on low priority_

I'm exploring providing a UI creating blocks, on [blockr.ui create-block branch](https://github.com/blockr-org/blockr.ui/tree/create-block)

The first issue I run into is the inability to edit a block given that we cannot re-register an existing block (with `register_block`)

**Comment by nbenn** [comment]
@JohnCoene I believe re-registering (i.e. overwriting an entry in the registry) is supported (with a warning). Ofc this can be extended, to silence the warning if `force = TRUE` or something like that.

If this does not work, could you supply an example? Happy to look into it.

**Comment by JohnCoene** [comment]
That looks to be for the workspace, I'm looking at the registry. When a block has need updated I should update it in the registry I believe.

**Comment by nbenn** [comment]
@JohnCoene I'm not talking about workspaces. What I meant: you should be able to call `register_block()` again to re-register. This will throw a warning if the block was already there. This warning we could disable with a `force` argument (currently not available but an easy things to add). Or if you have something else in mind, let me know.

**Comment by JohnCoene** [comment]
Ah OK indeed, sorry. All good then!

**Comment by nbenn** [comment]
@JohnCoene No worries! Let me know if something does not work as expected.
