### ISSUE TITLE
Arbitrary code block

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#239]
It'd be good to have an arbitrary code block. I believe the idea was given before as some form of "escape block" so that one can always create the necessary block if it does not exist in the registry.

Moreover, this is greatly reduces the time from script to blockr.

I'm happy to take this one with either the shinyace package or the ace editor directly.

**Comment by nbenn** [comment]
@JohnCoene I'm closing here, as I believe this was added to blockr.extra in https://github.com/blockr-org/blockr.extra/pull/7.
