### ISSUE TITLE
Delete stack

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#245]
In any application we'd need some functionality to delete any single stack.

I'm split about whether it should be within blockr or elsewhere, currently not being handled.

**Comment by nbenn** [comment]
As with many such things, I feel that blockr should provide the basic infrastructure to handle this. In principle, several things are already available:

- `rm_workspace_stack()` to manipulate the workspace
- Functionality in the workspace server function such as 
    https://github.com/blockr-org/blockr/blob/4124a23cfbb3121a71b93299707f7b10f749fc0b/R/server.R#L486

Now we currently have some issues with having the stack/workspace level server functions properly update (tracked in #234), but apart from that, are there things that we are missing?

**Comment by JohnCoene** [comment]
Agree that it should be in blockr.

UI:
- delete button

Server:
- removeUI
- remove from workspace
- reset inputs (optional)

---

I think we already have most required components: we just need a new button/link to delete in `.stack-tools`

https://github.com/blockr-org/blockr/blob/4124a23cfbb3121a71b93299707f7b10f749fc0b/R/ui.R#L355

And the corresponding server logic that can just `removeUI` and (optionally) remove/reset stack inputs (I rarely reset input values but @DivadNojnarg may have a different option, I think we do do that on block removal).

**Comment by JohnCoene** [comment]
Ah yes indeed, I forgot that.

It's something I had put in place for the demo and would have to be either removed or changed.

It's not good as it is, it makes the assumption that it uses masonry, etc.

`removeUI` is probably easier.

@DivadNojnarg do we need to propagate this to the blocks. We reset the inputs for the blocks when we remove a block, if we remove a stack should we reset the inputs of the children blocks too?

**Comment by DivadNojnarg** [comment]
No we don't reset because IDS are randomly generated and that does not seem to cause issues so far.

**Comment by DivadNojnarg** [comment]
In that case we could clean the JS code (which is probably easier if we assume blockr developers will mostly have a R background).

**Comment by JohnCoene** [comment]
I see some issues with how this is currently handled.

`inject_remove_button` is never called in `generate_ui.stack`

https://github.com/blockr-org/blockr/blob/0a4696821d9c48992131c69ab66bfbf6bd72dfd4/R/ui.R#L318

We build the UI differently from the workspace.

https://github.com/blockr-org/blockr/blob/0a4696821d9c48992131c69ab66bfbf6bd72dfd4/R/ui.R#L394
