### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#246]
Layout fields to be changed to an S3 class (`layout` arg or `new_block`).

@nbenn @DivadNojnarg any input?

**Comment by JohnCoene** [comment]
Note: we could probably remove many of the custom layout functions given the new default

**Comment by nbenn** [comment]
I might be a bit slow here, but could you elaborate a bit on what you mean by this? As is, I don't follow.

At some point we discussed having a generic function responsible for layouting instead of the `layout` arg in `new_block`. Is that what you mean?

**Comment by JohnCoene** [comment]
Yes, that's what I mean, I was thinking of simply changing this `layout` function from callback passed to `new_block` to an S3 method on the block.

```r
layout <- function(x, ...) UseMethod("layout")

layout.default <- function(x, ...){
   # current default here
}

# methods for specific blocks if necessary
layout.data_block <- function(x, ...){
   # ...
}
```

**Comment by nbenn** [comment]
Yes, that's a good idea I think. More consistent with the mechanics we have in place everywhere else.

Mini comment: the default method could be `layout.block()`. That way we have a clean error if dispatch happens on an object that does not inherit from block.

**Comment by DivadNojnarg** [comment]
@JohnCoene  You can skip the plot layout and ggiraph as I am cleaning them from the core. See #242.
