### ISSUE TITLE
Submit block

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#249]
@DivadNojnarg the submit block is pretty neat (!), only needs the `submit_block` class.

For #239 I use it to submit the code for the block, is there way to have it such that it "submits on load," e.g.: the default expression is `data` it should be valid but we have manually hit submit (see below).

![image](https://github.com/blockr-org/blockr/assets/7833796/bab4ab6a-5c6e-4f37-abe4-cc647e4469d1)

I might be missing something

**Comment by DivadNojnarg** [comment]
We are actually thinking to avoid passing that as a class but more as a block parameter. I am not sure you're missing something, there should be an autoclick feature which can be enabled or not on load but that's not implemented.

**Comment by nbenn** [comment]
@JohnCoene @DivadNojnarg changing how the submit functionality is implemented is being tracked in #162. The code block now lives in https://github.com/blockr-org/blockr.extra/pull/7. I'll therefore close here. Please re-open if I'm missing the point here.

Regarding the submit-on-load issue, I'm adding a note to #162.
