### ISSUE TITLE
Please allow blocks after plot blocks

### ISSUE THREAD

**Issue by karmatarap** [blockr-org/blockr#259]
I would like to use a function on ggstatsplot to extract stats from a statsplot object, can we please remove this line from stack.R
`     if (inherits(last, "plot_block")) {
       stop("Can't insert a block below a plot block.")
     }`

**Comment by DivadNojnarg** [comment]
How do you wanna move forward @nbenn?

- Should we accept the ongoing PR that simply removes the current check in `add_block` and follow up next week with something better with the registry (given what we discussed today, the registry metadata might be wrong ...)
- Or we don't allow adding block after a plot block until we have a clean solution, which can be an issue for the demo. I can check with @karmatarap.

**Comment by nbenn** [comment]
In my opinion, option 1 sounds good. I don't think we need to prevent adding blocks after a plot. If a block is implemented that can work with the result of a plot block, why not just pass this result onwards? Kind of like an `upload_block` returns a file path that can be consumed by a parser block.

So far we had a heavy focus on `data.frame`s but I think we want to generalize this (as we have been doing in the layer-by-layer plotting blocks). The more formal solution would be then to use `input` and `output` information from the registry. Until we have that you might run into an error that is not super informative if you combine incompatible blocks.
