### ISSUE TITLE
Facing the issue of fields is not updating in plot block, when I change the data

### ISSUE THREAD

**Issue by Ramdhadage** [blockr-org/blockr#265]

**Comment by Ramdhadage** [comment]
In below code when I changing the data from dataset block I am getting error:
library(shiny)
library(blockr.data)
library(blockr)
library(ggplot2)
devtools::load_all()

new_ggplot_block <- function(data, ...){
  col_names <- function(data) data |> 
    dplyr::select_if(is.numeric) |> # dropping non -numeric column
    purrr::discard(~ all(is.na(.))) |> 
    colnames()
  fields <- list(
    x = new_select_field(value = col_names(data)[1],choices =  col_names(data), type = "name"),
    y = new_select_field(col_names(data)[1], choices =  col_names(data), type = "name")
  )
  expr = quote(
    ggplot(mapping = aes(x = .(x), y = .(y)))
  )
  class = c("ggplot_block", "plot_block")
  new_block(fields = fields,
            expr = expr,
            class = class, ...)
}

ggplot_block <- function(data, ...) {
  initialize_block(new_ggplot_block(data, ...), data)
}

register_block(
  constructor = ggplot_block,
  name = "ggplot block",
  description = "Create the ggplot",
  classes = c("ggplot_block", "plot_block"),
  input = "data.frame",
  output = "list"
)

stack <- new_stack()
shinyApp(
  ui = bslib::page_fluid(
    add_block_ui(),
    generate_ui(stack, id = "mystack")
  ),
  server = function(input, output, session) {
    vals <- reactiveValues(new_block = NULL)
    stack <- generate_server(
      stack,
      id = "mystack",
      new_block = reactive(vals$new_block)
    )
    
    observeEvent(input$add, {
      vals$new_block <- NULL
      # Always append to stack
      loc <- length(stack$blocks)
      block <- available_blocks()[[input$selected_block]]
      # add_block expect the current stack, the block to add and its position
      # (NULL is fine for the position, in that case the block will
      # go at the end)
      vals$new_block <- list(
        block = block,
        position = loc
      )
    })
  }
)

![image](https://github.com/blockr-org/blockr/assets/16373721/baa7dedc-0592-49fc-a2ff-a178483efed9)

**Comment by DivadNojnarg** [comment]
Edited code:

```r
devtools::load_all()

library(shiny)
library(blockr.data)
library(ggplot2)

demo_data_block <- function(...) {
  initialize_block(
    new_data_block(
      ...,
      dat = as.environment("package:blockr.data"),
      selected = "lab"
    )
  )
}

custom_block <- function(data, ...) {
  initialize_block(new_block(
    # dummy field since we can't have block without fields (for now...)
    fields = list(dummy = new_string_field("test")),
    expr = quote({
        dplyr::select_if(.tbl = data, .predicate = is.numeric) %>% # dropping non -numeric column
        purrr::discard(~ all(is.na(.)))
    }),
    class = c("custom_block", "transform_block"),
    ...
  ), data)
}

new_ggplot_block <- function(data, ...){
  col_names <- function(data) colnames(data)
  fields <- list(
    x = new_select_field(colnames(data)[1], col_names(data), type = "name"),
    y = new_select_field(colnames(data)[2], col_names(data), type = "name")
  )
  expr <- quote(
    ggplot(mapping = aes(x = .(x), y = .(y)))
  )
  classes <- c("ggplot_block", "plot_block")
  new_block(fields = fields,
            expr = expr,
            class = classes, ...)
}

ggplot_block <- function(data, ...) {
  initialize_block(new_ggplot_block(data, ...), data)
}

register_blocks(
  constructor = c(ggplot_block, demo_data_block, custom_block),
  name = c("ggplot block", "demo data block", "custom block"),
  description = c("Create the ggplot", "Demo data block", "Custom wrangler block"),
  classes = list(
    c("ggplot_block", "plot_block"),
    c("demo_data_block", "data_block"),
    c("custom_block", "transform_block")
  ),
  input = c(NA_character_, "data.frame", "data.frame"),
  output = c("data.frame", "list", "data.frame")
)

stack <- new_stack()

shinyApp(
  ui = bslib::page_fluid(
    add_block_ui(),
    generate_ui(stack, id = "mystack")
  ),
  server = function(input, output, session) {
    vals <- reactiveValues(new_block = NULL)
    stack <- generate_server(
      stack,
      id = "mystack",
      new_block = reactive(vals$new_block)
    )
    
    observeEvent(input$add, {
      vals$new_block <- NULL
      # Always append to stack
      loc <- length(stack$blocks)
      block <- available_blocks()[[input$selected_block]]
      # add_block expect the current stack, the block to add and its position
      # (NULL is fine for the position, in that case the block will
      # go at the end)
      vals$new_block <- list(
        block = block,
        position = loc
      )
    })
  }
)
```

**Comment by nbenn** [comment]
@Ramdhadage (cc @DivadNojnarg) some comments on the issue you ran into:

- If you create a field as `new_select_field(colnames(data)[1], col_names(data))`, the choices will be fixed to the initial `data` value. If you want to have a dynamic column selection, you can pass a function with a `data` argument. You have already implemented `col_names()` in that way so you can pass this function as `choices` argument, for example like `new_select_field(colnames(data)[1], col_names)`. Doing that, your choices will become dynamic.
- For your implemenatation of `col_names()` as

    ```r
    col_names <- function(data) data |> 
      dplyr::select_if(is.numeric) |> # dropping non -numeric column
      purrr::discard(~ all(is.na(.))) |> 
      colnames()
    ```

    be aware that this does not modify the data (outside the scope of this function). This will only affect the choices you get in your drop-down. If you want to modify the data prior to plotting, you could add a separate block for that (in @DivadNojnarg's code snippet, this'd be the `custom_block`). You could of course also make this column-subsetting part of your expression in `new_ggplot_block()` prior to calling `ggplot()`.

- Ad @DivadNojnarg's comment in `custom_block()` regarding the need for at least one field: as of today, this is no longer the case. You could do

    ```r
    new_custom_block <- function(data, ...) {
      new_block(
        fields = list(),
        expr = quote({
          dplyr::select_if(.tbl = data, .predicate = is.numeric) %>%
          purrr::discard(~ all(is.na(.)))
        }),
        class = c("custom_block", "transform_block"),
        ...
      )
    }
    ```

Let me know if you have further questions.

**Comment by Ramdhadage** [comment]
Thank you so much for your help @DivadNojnarg @nbenn. After fallowing your step I am able to generate dynamic choices, but when I change the data I am getting null default values. I have attached the screenshot for your reference. Kindly help me with that.

```r 
new_ggplot_block <- function(data, ...){
  col_names <- function(data) colnames(data)
  x_default <- function(data) col_names(data)[1]
  y_default <- function(data) col_names(data)[2]  
  fields <- list(
    x = new_select_field(x_default, col_names, type = "name"),
    y = new_select_field(y_default, col_names, type = "name")
  )
  expr <- quote(
    ggplot(mapping = aes(x = .(x), y = .(y)))
  )
  classes <- c("ggplot_block", "plot_block")
  new_block(fields = fields,
            expr = expr,
            class = classes, ...)
}
```
![image](https://github.com/blockr-org/blockr/assets/16373721/3df74afa-74a4-48b2-b24a-fe75a759a3df)

**Comment by nbenn** [comment]
@Ramdhadage Thanks for reopening. That is a bug and I'm working on a fix.
