### ISSUE TITLE
Stack code copy

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#301]
During the demo the code copied by Karma did not look right. It look like the code included the dataset with `structure(...)` like it had been `dput`.

Trying to reproduce.

**Comment by JohnCoene** [comment]
This is caused by linked stacks (e.g.: join block), currently such blocks dump code

**Comment by DivadNojnarg** [comment]
I'l close this one in favor of #387 where we'll have to come up with a more general solution to export the code for an entire workspace, stack and beautify the code (the dataset code issue you mentioned has likely been fixed in 0.0.2 but the filter output is pretty ugly)
