### ISSUE TITLE
App Crash when I change the data for group by block 

### ISSUE THREAD

**Issue by Ramdhadage** [blockr-org/blockr#303]
App crashes when I fallow below steps:

1. add data block which have default date set as airquality.
2. add group by block.
3. change data to iris. 
Bug: App will crash 

![image](https://github.com/blockr-org/blockr.app/assets/16373721/6007de81-34ee-4f28-bf78-a06812abb3a2)
![image](https://github.com/blockr-org/blockr.app/assets/16373721/42d6f207-8456-423d-b48f-d6cb1eeb0762)

**Comment by DivadNojnarg** [comment]
Fixed in 0.0.2
