### ISSUE TITLE
App Crash when I change the data for select block

### ISSUE THREAD

**Issue by Ramdhadage** [blockr-org/blockr#304]
App crashes when I fallow below steps for:

1. Add data block which have default date set as airquality.
2. Add select block.
3. Change data to beaver1.
**Bug:** App will crash
![image](https://github.com/blockr-org/blockr.app/assets/16373721/e4cf0c0e-e2ad-4353-9754-8a1378932023)
![image](https://github.com/blockr-org/blockr.app/assets/16373721/5e62a72c-84db-4bbd-a5cd-dbe86a18b75d)

Same steps apply for arrange block it will crash again.

**Comment by DivadNojnarg** [comment]
Fixed in 0.0.2
