### ISSUE TITLE
Data block

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#316]
I have created packages for blocks to expose example datasets from the pharmaverse.

My approach is here

https://github.com/blockr-org/blockr.pharmaverseadam/blob/5cd7378dae0926ded7984222cb18e939b72ddee1/R/block.R#L15

@DivadNojnarg  Do you think this is viable? The advantage is that it does not require the packages to be loaded in the environment

**Comment by DivadNojnarg** [comment]
@JohnCoene in 0.0.2 (latest main) @nbenn reworked a bit the dataset block. Is this in line with what you expect?

**Comment by JohnCoene** [comment]
Sure works!
