### ISSUE TITLE
Package versioning

### ISSUE THREAD

**Issue by nbenn** [blockr-org/blockr#377]
Let's start doing this. @JohnCoene what is the current commit in place at BMS?

**Comment by JohnCoene** [comment]
What is in place is what is on the [forward](https://github.com/blockr-org/blockr/tree/forward) branch.

This mainly includes:

- Add blocks PR #325 
- Expose inputs PR #337 
- Safely evaluate blocks to avoid crashes 57c1190f379207207b3cb71a948330661a56f593
- The filebrowser block needs to read from root 5907e3adad45a5d14571a62c040ea40f929c5a40

I'm pretty certain there is a fix to the stack title edit somewhere but I can't find it back, it would easy and quick for me to reimplement anyway.
