### ISSUE TITLE
Code Generation

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#39]
We generate code for each individual block but the user probably wants to be able to copy the code for the entire stack

**Comment by nbenn** [comment]
@JohnCoene To make this a bit more actionable on my side:

Currently we have code generation at the block level (the `generate_code()` generic only is implemented for blocks so far). Is what you're asking for simply a method for an entire stack? I could provide a method `generate_code.stack()` that does this for you. It'd call the block level `generate_code()` implementations and put everything together by piping results.

**Comment by JohnCoene** [comment]
Yes, that would work, thank you!
