### ISSUE TITLE
Remove block does not update downstream data

### ISSUE THREAD

**Issue by DivadNojnarg** [blockr-org/blockr#57]
Scenario:

- Add data block -> 50000 rows
- Add filter block -> 1000 rows
- Add select block  -> 1000 rows 1col

Remove filter block. We still see 1000 rows, the select_block is using the old data.

I guess we would have to reinitialise all the downstream stack whenever a block is removed, so the data state is correct?

**Comment by christophsax** [comment]
@DivadNojnarg Looks like fixed? Please reopen if not.
