### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by DivadNojnarg** [blockr-org/blockr#65]
Explain block concept, fields, ...

**Comment by christophsax** [comment]
Would it make sense to consolidate with what we have here? https://github.com/blockr-org/blockr/wiki/Architecture

Documentation for block authors and for us could live at the same place?

**Comment by christophsax** [comment]
Combine with:

https://blockr-org.github.io/blockr/articles/developer-guide.html

**Comment by christophsax** [comment]
We have already quite something from @DivadNojnarg  as user documentation. Linked there from the wiki.
