### ISSUE TITLE
Classes ~ Inheritance

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#75]
All objects are custom classes and do not inherit from R built-ins, is that on purpose?
Applies to stack, block, and field

E.g.: https://github.com/blockr-org/blockr/blob/9c88b24a7597ff86af5b69714f25952778d391da/R/block.R#L40

Could we have

```r
structure(
  obj,
  class = c("newClass", class(obj))
)
```

That would allow for, e.g.: `jsonlite::toJSON(obj)`, currently fails due to unimplemented method.

I'll force conversion for the serialisation.

**Comment by nbenn** [comment]
i don't believe that having *all* our objects inherit from a base type is a sensible requirement, just for making jsonlite happy. There are many other (better) ways around this.

Using built in jsonlite functionality:

```r
my_oby <- structure(
  list(key1 = "val1", key2 = "val2"),
  class = "my_cls"
)

jsonlite::serializeJSON(my_oby)
#> {"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["key1","key2"]},"class":{"type":"character","attributes":{},"value":["my_cls"]}},"value":[{"type":"character","attributes":{},"value":["val1"]},{"type":"character","attributes":{},"value":["val2"]}]}

jsonlite::toJSON(my_oby, force = TRUE)
#> {"key1":["val1"],"key2":["val2"]}
```

Injecting our own custom code into the jsonlite stack:

```r
jsonlite::toJSON(my_oby)
#> Error: No method asJSON S3 class: my_cls

setOldClass("my_cls")

setMethod(
  getGeneric("asJSON", package = "jsonlite"),
  "my_cls",
  function(x, ...) jsonlite::toJSON(paste(x$key1, x$key2))
)

jsonlite::toJSON(my_oby)
#> ["val1 val2"]
```

Or of course building introducing our own generic function for serialization, which would afford the greatest flexibility (at little cost).

**Comment by JohnCoene** [comment]
Apologies, I don't understand why "I don't believe that having all our objects inherit from a base type is a sensible requirement".

I just used jsonlite as an example, it's safe to assume it is going to cause issues elsewhere.

**Comment by nbenn** [comment]
In the case of jsonlite, what good is an object serialized as

```r
my_obj <- structure(
  list(key1 = "val1", key2 = "val2"),
  class = c("my_cls", "list")
)

jsonlite::toJSON(my_obj)
#> {"key1":["val1"],"key2":["val2"]}
``` 

how are you going to deserialize this object later? You no longer know the type.

We need at least a bit of control over how our objects are serialized, which is why I made suggestions

- injecting our own custom code into the jsonlite stack
- introducing our own generic function for serialization

(or do a "brute-force serialization as `jsonlite::serializeJSON()` which is probably more verbose than necessary and we *still* might want to be able to inject or own logic for introducing a version number for example). Neither of those suggestions require our objects to inherit from a base type.

So no, I don't think the example of jsonlite is reasonable for requiring all objects to inherit from a base type.

> it's safe to assume it is going to cause issues elsewhere

Do you have examples of such issues that we could consider? I'm happy to discuss them.

**Comment by JohnCoene** [comment]
Again, I was just using serialising as an example because that is what I encountered. If I encounter it with jsonlite another user can encounter it.

I did not suggest we do so for our own serialisation, just to make sure it works for users in the future.

What If a user wants to `session$sendCustomMessage("msg", stack)`.

I don't want to spend time scouring CRAN for packages where it could cause issues but I'd imagine similar issues could be encountered in DBI for instance.

I still do not understand what is the added benefit of such a restrictive class.

We can park this for now.

**Comment by nbenn** [comment]
@JohnCoene 

> I still do not understand what is the added benefit of such a restrictive class.

It is the other way round: the requirement that every one of our S3 classes also inherit from a base type is the more "restricted" setting. It is for doing that, that we need good reasons.

I cannot think of such reasons and so far, you have not provided any.

-  > If a user wants to `session$sendCustomMessage("msg", stack)`?

    They should not want to do that. By doing that they now depend on the internal representation of the stack class. This will most likely not ever be part of a stable API. Instead they might do something like `session$sendCustomMessage("msg", to_string(stack))`. With such a design, the internal representation of the stack class can be decoupled from what the user gets by calling `to_string()` and we can at least try to maintain a stable interface via such an abstraction. In this case it is a good thing that jsonlite throws an error.
- > I don't want to spend time scouring CRAN for packages where it could cause issues

    Neither do I. But what would the point of such an exercise be? You will find functions in packages on CRAN where passing a stack object will throw an error. But this is the case irrespective of whether "stack" inherits from "list" or not.
    
- > I'd imagine similar issues could be encountered in DBI

    Can you be more specific? What kind of issue are we talking about? Can you make an example? DBI does not do ORM. It's "table in/table out".

If you believe this is this a common design pattern and deviating from this needs justification, can you point me to (widely used) S3 classes that are implemented in such a way?

Off the top of my head, I don't know of any good examples for this.

```r
attr(data.frame(), "class")
#> [1] "data.frame"
attr(factor(), "class")
#> [1] "factor"
attr(Sys.time(), "class")
#> [1] "POSIXct" "POSIXt"
attr(
  dbplyr::lazy_frame(a = TRUE, b = 1, c = 2, d = "z",
                     con = dbplyr::simulate_sqlite()),
  "class"
)
#> [1] "tbl_SQLiteConnection" "tbl_lazy"             "tbl"
attr(zoo::as.zoo(rnorm(5)), "class")
#> [1] "zoo"
```
