### ISSUE TITLE
Attributes consistency

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#76]
Blocks have a `name`

https://github.com/blockr-org/blockr/blob/9c88b24a7597ff86af5b69714f25952778d391da/R/block.R#L38

Fields have a `type`

https://github.com/blockr-org/blockr/blob/9c88b24a7597ff86af5b69714f25952778d391da/R/field.R#L22

Should we align/standardise?

**Comment by nbenn** [comment]
@JohnCoene sorry that this was left unanswered for so long. I agree with you that we should be consistent in how we name things and for sure there are things that can be improved.

The current example however is not something where I think we are being inconsistent: block names and field types are two separate things. The `type` argument for fields is more related how it behaves in an expression (whether it represents a literal or a name). Maybe `type` is a bit generic for this and I'm happy to take suggestions to improve the situation.

I want to refactor block names/IDs such that the name is handed out (if not specified by the user and checked for uniqueness) by the corresponding stack (#127), so this argument will go away anyways.

I'm closing this as currently it is not actionable. Please feel free to re-open if you have other naming inconsistencies to sort through.
