### ISSUE TITLE
Generate Code Method

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#79]
Should things like these be methods?

https://github.com/blockr-org/blockr/blob/9c88b24a7597ff86af5b69714f25952778d391da/R/block.R#L78

Extending for new block may require a special case/`if` and a PR in {blockr}?

**Comment by christophsax** [comment]
It could be done in a better way. Use S3 dispatch.

**Comment by DivadNojnarg** [comment]
Closed in #107.
