### ISSUE TITLE
Is truthy

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#80]
It looks like this function is copied from `shiny::isTruthy`

https://github.com/blockr-org/blockr/blob/9c88b24a7597ff86af5b69714f25952778d391da/R/utils.R#L144

Should we not just depend on Shiny which is already a dependency?

**Comment by nbenn** [comment]
The reason for pulling in this function was trying to avoid shiny dependencies outside of clearly shiny related functions such as the ui/server generics. I agree that with what we currently have, this is dumb. At the same time I still feel that (medium term) it could be a good thing to have shiny stuff in a separate package. Not sure where this leaves us on this questions then.

**Comment by JohnCoene** [comment]
Ok, I guess we can park it for now and see where we go with the idea of taking shiny away from this package

**Comment by christophsax** [comment]
Ok if I close this, then? Helps me to keep the overview of what's still open.
