### ISSUE TITLE
Evaluate on initialise

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#82]
Should we really evaluate blocks on initialisation?

Isn't that likely to cause issues?

e.g.: 

```r
s <- new_stack(demo_data_block, select_block)
```
```
Error in `dplyr::select()`:
! Can't subset columns that don't exist.
✖ Column `columns` doesn't exist.
Run `rlang::last_trace()` to see where the error occurred.
```

https://github.com/blockr-org/blockr/blob/9c88b24a7597ff86af5b69714f25952778d391da/R/stack.R#L20

**Comment by christophsax** [comment]
Related to #78

**Comment by DivadNojnarg** [comment]
Closing, this has been reworked in 0.0.2 with the new validation and initialisation models.
