### ISSUE TITLE
Workspace class

### ISSUE THREAD

**Issue by christophsax** [blockr-org/blockr#92]
As discussed today, it would make sense to prioritize it, despite what we said last Friday. @nbenn is drafting, and discusses with @JohnCoene afterwards.

**Comment by christophsax** [comment]
We schedule a meeting next week, Tue 5pm. A lot to discuss and think about.

**Comment by christophsax** [comment]
Shiny logic in #121

**Comment by DivadNojnarg** [comment]
After #124, it is possible that the workspace has to be a structure, similar to what we have for stacks and blocks.
