### ISSUE TITLE
Provide Admiral example script

### ISSUE THREAD

**Issue by christophsax** [blockr-org/blockr#95]

**Comment by karmatarap** [comment]
Please use this example https://github.com/pharmaverse/admiral/blob/main/inst/templates/ad_adae.R

The dataset used is from pharmaversesdtm, which is the same source as the blockr.data package (will need the ae dataset)

**Comment by DivadNojnarg** [comment]
Done in https://github.com/blockr-org/blockr.extra/blob/main/R/admiral-dpc-block.R
