### ISSUE TITLE
Summarize blocks - crash

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#98]
I have to record a demo for @karmatarap tomorrow but the summarize block crashes on the latest `main` (subscript out of bounds)

Sorry @DivadNojnarg, this is a bit urgent, do you have the time to look at it today?

**Comment by DivadNojnarg** [comment]
Yes it's because the default params for summarize block went away :). Thanks for checking.

**Comment by DivadNojnarg** [comment]
See #100
