### ISSUE TITLE
Remove block - crash

### ISSUE THREAD

**Issue by JohnCoene** [blockr-org/blockr#99]
App crashes when removing a block: subscript out of bounds.

Seems to me like it is caused by

https://github.com/blockr-org/blockr/blob/c5c6be64d1cb65ded2b16acf7bdeb7cadcfae979/R/server.R#L374

E.g.: remove last block of a stack of 2: `to_remove == 2`, for loop attempts to access index `2` which does not exist.

**Comment by DivadNojnarg** [comment]
@JohnCoene: I pushed a hotfix in main. Can you check?

**Comment by JohnCoene** [comment]
demo summarize block works now, haven't tested the standard block though. Thanks @DivadNojnarg !

**Comment by DivadNojnarg** [comment]
I fixed the default one but not yet on main. If you can work with the demo block, this is fine. I'll submit the MR later.
